[  
   {  
      "id":9,
      "volunteer_id":25,
      "responder":"",
      "call_date_minute":30,
      "call_date_hour":17,
      "call_date_dayofmonth":28,
      "call_date_month":5,
      "call_date_year":2011,
      "call_from":"",
      "caller_name":"",
      "caller_phone_number":"",
      "call_location":"",
      "call_species":"",
      "when_first_seen":"",
      "call_comments":"",
      "call_referred_to":"",
      "call_condition":"",
      "investigator_support":"Casey Mclean",
      "investigation_date_minute":30,
      "investigation_date_hour":17,
      "investigation_date_dayofmonth":28,
      "investigation_date_month":5,
      "investigation_date_year":2011,
      "investigation_lat_lon_location":"",
      "investigation_physical_location":"Lime Kiln Land Bank Side",
      "investigation_species":"Harbor Porpoise",
      "animal_not_found":false,
      "investigation_condition":"Dead Stinky",
      "tags":"",
      "disposition":"Left at site",
      "seal_pickup":"",
      "sex":"Female",
      "weight":0,
      "straight_length":173,
      "contour_length":0,
      "girth":0,
      "is_photo_taken":true,
      "investigation_comments":"The length measurement is an approx. She was on her side. Lower jaw, skin samples and fetus were taken. She was located on the beach north of the lime kilns on the far right end (north?). ",
      "attachments":[  

      ]
   },
   {  
      "id":8,
      "volunteer_id":32,
      "responder":"Amy",
      "call_date_minute":0,
      "call_date_hour":12,
      "call_date_dayofmonth":21,
      "call_date_month":5,
      "call_date_year":2011,
      "call_from":"Other",
      "caller_name":"",
      "caller_phone_number":"",
      "call_location":"American Camp - San Juan Island",
      "call_species":"Other",
      "when_first_seen":"",
      "call_comments":"Dall's \/ Harbor hybrid",
      "call_referred_to":"",
      "call_condition":"Dead",
      "investigator_support":"Amy T \/ Karl K \/ Deb S \/ Casey M \/ Nan S \/ Steve S \/ Dan",
      "investigation_date_minute":30,
      "investigation_date_hour":7,
      "investigation_date_dayofmonth":22,
      "investigation_date_month":5,
      "investigation_date_year":2011,
      "investigation_lat_lon_location":"N 48 27 27.72 - W 123 01 00.46",
      "investigation_physical_location":"2nd cove east of Granny's",
      "investigation_species":"Other",
      "animal_not_found":false,
      "investigation_condition":"Dead Fresh",
      "tags":"none",
      "disposition":"Collected",
      "seal_pickup":"",
      "sex":"Female",
      "weight":0,
      "straight_length":0,
      "contour_length":0,
      "girth":0,
      "is_photo_taken":false,
      "investigation_comments":"See necropsy report and measurement data collected.",
      "attachments":[  

      ]
   },
   {  
      "id":12,
      "volunteer_id":35,
      "responder":"",
      "call_date_minute":0,
      "call_date_hour":12,
      "call_date_dayofmonth":2,
      "call_date_month":6,
      "call_date_year":2011,
      "call_from":"",
      "caller_name":"",
      "caller_phone_number":"",
      "call_location":"12 calderone Rd, neck Point, Shaw Island",
      "call_species":"Harbor Seal",
      "when_first_seen":"",
      "call_comments":"",
      "call_referred_to":"",
      "call_condition":"",
      "investigator_support":"Mack Davis\/Nancy Potts",
      "investigation_date_minute":45,
      "investigation_date_hour":10,
      "investigation_date_dayofmonth":2,
      "investigation_date_month":6,
      "investigation_date_year":2011,
      "investigation_lat_lon_location":"",
      "investigation_physical_location":"12 Calderone rd, Neck Point, Shaw Island",
      "investigation_species":"Harbor Seal",
      "animal_not_found":false,
      "investigation_condition":"Dead Fresh",
      "tags":"",
      "disposition":"Left at site",
      "seal_pickup":"",
      "sex":"Unknown",
      "weight":0,
      "straight_length":162,
      "contour_length":182,
      "girth":0,
      "is_photo_taken":true,
      "investigation_comments":"Found seal at address, seal lying on beach, head under a log, removed log, observed the head was significantly scavenged, along with the taiil end. nable to determine sex due to scavenged tail. the only other wound was at the right chest area. There was no other wound or scavenged aea. I attempted to pull some teeth. I pulled two canines, one fromthe upper left and one from the lower right. The canine from the lower left was missing. I also pulled some of the smaller teeth. All teeth pulled came out very easily , as if there were no roots. Nine pictures were taken at this time. I also marked the seal so owner of property knew we were there. ",
      "attachments":[  
         {  
            "id":8,
            "file_name":"100_10571.JPG",
            "comments":""
         },
         {  
            "id":9,
            "file_name":"100_10581.JPG",
            "comments":""
         },
         {  
            "id":10,
            "file_name":"100_1059.JPG",
            "comments":""
         }
      ]
   }
]
